config/routes.rb
Rails.application.routes.draw do

  mount Admin::Engine, at: "admin"

  namespace :api, defaults: { format: :json } do
    namespace :v1, version: :v1, module: :v1 do

      scope :billing do
        put :sku, to: 'products#update'
        put :billable, to: 'orders#update'
        delete :billable, to: 'orders#destroy'
      end

      scope :data do
        get '/chart/(:type)/(:id)', to: 'data#show', as: :chart_type
        get '/chart/(:type)/(:start_date)/(:end_date)', to: 'data#show', as: :chart_date_range
      end

    end
  end

  get '/dashboard', to: 'dashboard#index'

  #resources :users

  devise_for :users, skip: [:sessions, :passwords, :confirmations, :registrations, :unlocks]

  devise_scope :user do

    authenticated :user do
      root to: 'dashboard#index'

      get 'dashboard', to: 'dashboard#index', as: :dashboard_home
      get 'dashboard/:type', to: 'dashboard#show', as: :dashboard_type
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: 'new_user_session'
    end

    post '/login', to: 'devise/sessions#create', as: 'user_session'
    get '/logout', to: 'devise/sessions#destroy', as: 'destroy_user_session'

    get '/join', to: 'devise/registrations#new', as: 'new_user_registration'
    post '/join', to: 'devise/registrations#create', as: 'user_registration'

    scope '/account' do

      get '/verification', to: 'devise/confirmations#verification_sent', as: 'user_verification_sent'
      get '/confirm', to: 'devise/confirmations#show', as: 'user_confirmation'
      get '/confirm/resend', to: 'devise/confirmations#new', as: 'new_user_confirmation'
      post '/confirm', to: 'devise/confirmations#create'

      get '/reset-password', to: 'devise/passwords#new', as: 'new_user_password'
      get '/reset-password/change', to: 'devise/passwords#edit', as: 'edit_user_password'
      put  '/reset-password', to: 'devise/passwords#update', as: 'user_password'
      post '/reset-password', to: 'devise/passwords#create'

      post '/unlock', to: 'devise/unlocks#create', as: 'user_unlock'
      get '/unlock/new', to: 'devise/unlocks#new', as: 'new_user_unlock'
      get '/unlock', to: 'devise/unlocks#show'

      get '/cancel', to: 'devise/registrations#cancel', as: 'cancel_user_registration'
      get '/settings', to: 'devise/registrations#edit', as: 'edit_user_registration'
      put '/settings', to: 'devise/registrations#update'

      delete '', to: 'devise/registrations#destroy'

    end

  end

end

app/views/layouts/partials/_favicon.html.haml
= favicon_link_tag "favicon/apple-touch-icon-57x57.png", rel: "apple-touch-icon-precomposed", sizes: "57x57"
= favicon_link_tag "favicon/apple-touch-icon-114x114.png", rel: "apple-touch-icon-precomposed", sizes: "114x114"
= favicon_link_tag "favicon/apple-touch-icon-72x72.png", rel: "apple-touch-icon-precomposed", sizes: "72x72"
= favicon_link_tag "favicon/apple-touch-icon-144x144.png", rel: "apple-touch-icon-precomposed", sizes: "144x144"
= favicon_link_tag "favicon/apple-touch-icon-60x60.png", rel: "apple-touch-icon-precomposed", sizes: "60x60"
= favicon_link_tag "favicon/apple-touch-icon-120x120.png", rel: "apple-touch-icon-precomposed", sizes: "120x120"
= favicon_link_tag "favicon/apple-touch-icon-76x76.png", rel: "apple-touch-icon-precomposed", sizes: "76x76"
= favicon_link_tag "favicon/apple-touch-icon-152x152.png", rel: "apple-touch-icon-precomposed", sizes: "152x152"
= favicon_link_tag "favicon/favicon-196x196.png", rel: "icon", sizes: "196x196", type: "image/png"
= favicon_link_tag "favicon/favicon-96x96.png", rel: "icon", sizes: "96x96", type: "image/png"
= favicon_link_tag "favicon/favicon-32x32.png", rel: "icon", sizes: "32x32", type: "image/png"
= favicon_link_tag "favicon/favicon-16x16.png", rel: "icon", sizes: "16x16", type: "image/png"
= favicon_link_tag "favicon/favicon-128.png", rel: "icon", sizes: "128x128", type: "image/png"

%meta{content: "", name: "application-name"}
%meta{content: "#FFFFFF", name: "msapplication-TileColor"}
%meta{content: "/assets/favicon/mstile-144x144.png", name: "msapplication-TileImage"}
%meta{content: "/assets/favicon/mstile-70x70.png", name: "msapplication-square70x70logo"}
%meta{content: "/assets/favicon/mstile-150x150.png", name: "msapplication-square150x150logo"}
%meta{content: "/assets/favicon/mstile-310x150.png", name: "msapplication-wide310x150logo"}
%meta{content: "/assets/favicon/mstile-310x310.png", name: "msapplication-square310x310logo"}

app/views/layouts/partials/_header.html.haml
.brand
  %a.logo{href: root_url}
    %i.fa.fa-lg.fa-space-shuttle.hidden-xs
    %span.hidden-xs ROCKETBOARD

%ul.nav.navbar-nav.navbar-left
  %li.toggle-navigation.toggle-left
    %button#toggle-left.sidebar-toggle
      %i.fa.fa-bars

%ul.nav.navbar-nav.navbar-right
  %li.dropdown.profile
    %a.dropdown-toggle{"data-toggle" => "dropdown", href: "javascript:void(0);"}
      %span.meta
        %span.avatar
          = image_tag current_user.try(:gravatar_url), class: 'img-circle'
        %span.text
          = current_user.try(:email)
        %span.caret
    %ul.dropdown-menu.animated.fadeIn{role: :menu}
      %span.arrow.top
      %li
        = link_to destroy_user_session_path, method: :delete do
          %span.icon
            %i.fa.fa-power-off
            Log out

app/views/layouts/partials/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/partials/_sidebar.html.haml
%h5.sidebar-header

%nav

  %ul.nav.nav-pills.nav-stacked

    %li{class: "#{:active if controller?('dashboard') && action?('index')}"}
      = link_to dashboard_path do
        %i.fa.fa-fw.fa-cubes
        Dashboard

    %li{class: "nav-dropdown #{'active open' if controller?('dashboard') && action?('show')}"}
      = link_to '#' do
        %i.fa.fa-fw.fa-tachometer
        Performance
      %ul.nav-sub
        %li{class: "#{:active if controller?('dashboard') && action?('show') && params[:type] == :customers}"}
          = link_to dashboard_type_path(:customers) do
            %i.fa.fa-fw.fa-user
            Customers
        %li{class: "#{:active if controller?('dashboard') && action?('show') && params[:type] == :products}"}
          = link_to dashboard_type_path(:products) do
            %i.fa.fa-fw.icon-layers
            Products